import Link from "next/link";
import { ArrowRight, Building2, FileBarChart, CheckCircle2, ShieldCheck, TreeDeciduous } from "lucide-react";

export default function EnterprisePage() {
  return (
    <div className="flex flex-col gap-24 pb-20">
      {/* Hero Section */}
      <section className="relative pt-24 pb-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-center w-full">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-900/20 via-background to-background"></div>
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border border-blue-500/30 text-blue-400 text-sm font-medium mb-8">
          <Building2 className="w-4 h-4" />
          <span>B2B Sustainability Infrastructure</span>
        </div>
        <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-8">
          Automated ESG Compliance <br/>
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-indigo-400">At Scale.</span>
        </h1>
        <p className="text-xl text-gray-400 max-w-3xl mx-auto mb-10 text-balance leading-relaxed">
          EarthElix Enterprise seamlessly integrates with corporate logistics, automatically logging every diverted kilogram of waste directly to a unified carbon ledger for guaranteed Scope 3 compliance.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
          <button className="w-full sm:w-auto px-8 py-4 rounded-full bg-blue-600 hover:bg-blue-500 text-white font-semibold transition-all hover:shadow-[0_0_30px_-5px_rgba(37,99,235,0.5)] flex items-center justify-center gap-2 group">
            Book an Architecture Review <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
          </button>
        </div>
      </section>

      {/* Core Features Grid */}
      <section className="px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto w-full">
        <div className="grid md:grid-cols-3 gap-8">
          <div className="glass-card p-8 rounded-3xl border-t border-t-white/10 hover:border-blue-500/30 transition-colors">
            <div className="w-12 h-12 rounded-xl bg-blue-500/10 flex items-center justify-center mb-6">
              <FileBarChart className="w-6 h-6 text-blue-400" />
            </div>
            <h3 className="text-xl font-bold text-white mb-4">Tax & ESG Export API</h3>
            <p className="text-gray-400">
              One-click extraction of verified diversion metrics. Streamline environmental tax write-offs with government-compliant logging formats.
            </p>
          </div>

          <div className="glass-card p-8 rounded-3xl border-t border-t-white/10 hover:border-indigo-500/30 transition-colors">
            <div className="w-12 h-12 rounded-xl bg-indigo-500/10 flex items-center justify-center mb-6">
              <ShieldCheck className="w-6 h-6 text-indigo-400" />
            </div>
            <h3 className="text-xl font-bold text-white mb-4">Tamper-Proof Ledger</h3>
            <p className="text-gray-400">
              Every pickup is cryptographically signed upon completion by both smart sensors and verified drivers, eliminating "greenwashing" risk.
            </p>
          </div>

          <div className="glass-card p-8 rounded-3xl border-t border-t-white/10 hover:border-blue-500/30 transition-colors">
            <div className="w-12 h-12 rounded-xl bg-blue-500/10 flex items-center justify-center mb-6">
              <TreeDeciduous className="w-6 h-6 text-blue-400" />
            </div>
            <h3 className="text-xl font-bold text-white mb-4">Automated Carbon Offsets</h3>
            <p className="text-gray-400">
              Directly purchase fractionalized carbon credits in real-time as negative emissions are generated by your fleet optimization.
            </p>
          </div>
        </div>
      </section>

      {/* Mock Integration Code */}
      <section className="px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto w-full text-center">
        <h2 className="text-3xl font-bold mb-4">Developer-First Integration</h2>
        <p className="text-gray-400 mb-8 max-w-2xl mx-auto">Embed the EarthElix compliance engine directly into your existing ERP systems with just a few lines of code.</p>
        
        <div className="text-left bg-[#0d1117] rounded-2xl p-6 border border-white/10 font-mono text-sm shadow-2xl relative overflow-hidden group">
          <div className="absolute top-0 right-0 px-4 py-2 bg-white/5 text-gray-500 text-xs font-semibold rounded-bl-xl border-b border-l border-white/10">
            Node.js / TypeScript
          </div>
          <pre className="text-gray-300">
            <code className="text-purple-400">import</code> {'{'} EarthElixClient {'}'} <code className="text-purple-400">from</code> <code className="text-green-300">'@earthelix/sdk'</code>;<br/><br/>
            <code className="text-purple-400">const</code> elix = <code className="text-purple-400">new</code> EarthElixClient(process.env.EARTHELIX_API_KEY);<br/><br/>
            <code className="text-gray-500">// Trigger automated pickup & calculate estimated offset</code><br/>
            <code className="text-purple-400">const</code> response = <code className="text-purple-400">await</code> elix.logistics.requestPickup({'{'}<br/>
            {'  '}locationId: <code className="text-green-300">'warehouse-7B'</code>,<br/>
            {'  '}estimatedWeightKg: <code className="text-yellow-300">450.5</code>,<br/>
            {'  '}autoAssign: <code className="text-purple-400">true</code><br/>
            {'}'});<br/><br/>
            console.log(<code className="text-green-300">`Pickup scheduled. Est CO2 offset: ${'{'}response.estimatedCarbonOffsetKg{'}'}kg`</code>);
          </pre>
        </div>
      </section>
    </div>
  );
}
